quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=lemark_admin
quarkus.datasource.password=lemark_admin
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/lemark_catalogue
quarkus.hibernate-orm.database.generation=validate